### PR TITLE
Bump version for testing

### PR DESCRIPTION
**Pull request by danbishop**

### CODE REVIEW

**Comment by danbishop** [comment]
Could we get the latest version on one of the testing channels? :)

**Comment by IsaacJT** [comment]
Hi @danbishop,

Thanks for this - can you please rebase against the latest main? I've added a GitHub workflow to test if the snap builds in PRs.

**Comment by danbishop** [comment]
Done. Great work adding the test!

**Comment by IsaacJT** [comment]
Hi Dan,

Sorry to be a pain but can you please rebase instead of merging? That way there's no unnecessary merge commit.

Cheers

**Comment by danbishop** [comment]
Sorry Isaac... think that's how it should be now.

**Comment by IsaacJT** [comment]
That's perfect - thanks!

**Comment by IsaacJT** [comment]
This is now available in the latest/beta channel

**Pull request merged**
